### ISSUE TITLE
Pre-release versions roadmap

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-2#9]
### Alpha 1
 - [ ] About page (Alpha version)
 - [ ] Overview page (Alpha version)
 - [ ] Keyboard listeners / Multi-select
 - [ ] History
 - [x] Glyphr Studio alpha branding
 - [ ] Other sites: Blog
 - [ ] Other sites: Help
 - [ ] Other sites: Main site with Alpha information

 
**Random bugs**
 - [ ] Space glyph tile
 - [ ] select a character with no glyph yet created
 - [ ] panel FOUC

### Alpha 2
 - [ ] New Project page (Alpha version)
 - [ ] Import / Export OTF
 - [ ] Settings page
 - [ ] Live Preview page

### Beta 1
- [ ] Import / Export SVG
- [ ] Ligatures
- [ ] Glyphr Studio v2 branding

### Beta 2
- [ ] Components
- [ ] Kerning
- [ ] Global actions

### V2.0.1
- [ ] Cross-project actions

**Comment by mattlag** [comment]
Turned all these into issues and added them to the Project board.
