### ISSUE TITLE
Beta 1 Release Checklist

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-2#99]
### Blog
- [x] Write blog article
- [x] Beta-1 blog link: Main Site
- [x] Beta-1 blog link: v2 Site
- [x] Beta-1 blog link: Help Site
- [x] Beta-1 blog link: App

### Branding
 - [x] Main site v2 Logo
 - [x] V2 site v2 Logo
 - [x] Help site v2 Logo

### App
 - [x] Build and upload v2 App
 - [x] Release on GitHub
 - [x] Release note on Help site

### Other Sites
 - [x] upload Help site
 - [x] upload Main site with new v2 section
